Homework 3
Kolesov-Dmitry/homework pull request #3
Opened 2021-04-20 04:25 UTC by Kolesov-Dmitry

Евгений, добрый день!

С трудом далось мне это задание, в итоге два раза переделывал и всё равно остался костыль, который мозолит глаза, но избавиться от него не получилось. Так и не придумал как красиво для разных форматов данных (html, json, csv) сделать ответ на запрос DELETE, Сначала выделил под каждый формат свой ResponseWriter, но по сути они отличались только методом ответа на DELETE запрос. Мне не понравилось и я оставил один общий ResponseWriter c костылём для HTML формата.

Был бы очень рад, если бы вы направили меня в этом вопросе на правильную мысль :)

Так же хотелось обойтись без синглтонов, это привело к тому, что пришлось пробросить фабрику рендеров в обёртку Handler. Опять же из-за HTML формата для которого надо грузить шаблоны, которые могут грузиться долго и хочется делать это всего один раз во время запуска сервера.

В остальном заколхозил простейший маршалер для CSV (всегда был уверен, что он идёт с Go из коробки, а оказалось...)
Будет время, допишу и закину тесты на всё это безобразие.

2021-04-21 08:28 UTC, goarchitecture requested changes
Вполне хорошо. По поводу сложностей с рендерингом.
Добавление метода GetContentType() - слишком узко. А если ещё какие-то модификации респонса потребуются - ещё хедеры и т.д.

JsonRendered/CsvRenderer/HtmlRenderer - предлагаю оставить их простыми, выполняющих одну задачу: из полученного объекта модели (или коллекции моделей) рендерить []byte. Всё. Больше они ничего знать не должны. Так их легко писать, читать и тестить.

Дальше, можно сделать рендерер другого уровня. К примеру: HttpRenderer или ResponseRenderer (или назвать ContentWriter и т.д.)
У него уже контент готовый есть, он заботится о том, как этот контент вставить в ResponseWriter.
Он может иметь доступ к ResponseWriter и Request (чтобы считать ?download к примеру). На вход он получает готовый []byte и он, зная какой это запрос (какой эндпоинт) - строит нужные хедеры. Да, формат он тоже считывает с ?format

Тут есть два варианта:
HttpRenderer считывает ?format и через фабрику вызывает NewRenderer(format).Render(obj) и получает []byte
Но тогда усложняется их тестирование. Получается тестируя HttpRenderer мы должны делать мок на внутренний рендерер. Поэтому я предлагаю их разделить, и он будет получать уже готовый []byte как параметр

2021-04-21 08:28 UTC, goarchitecture commented on internal/render/html_renderer.go
> +	if val.Kind() == reflect.Ptr {
reflect.Indirect()

2021-04-21 08:28 UTC, goarchitecture commented on internal/srv/middleware.go
> +		if _, ok := query["download"]; ok {
download=false не должно срабатывать загрузку.
Фронтенду нужно разрешить такую возможность, для фронтенда может быть удобнее делать что-то типа `?download={downloadIsNeeded}` вмест того, чтобы строить if else и прятать download вовсе если он не запрошен

2021-04-21 08:28 UTC, goarchitecture commented on internal/srv/middleware.go
> +func downloadMiddleware(h http.Handler) http.Handler {
а нужно ли middleware? для 2 эндпоинтов? get/getAll только нуждаются в этом флаге

2021-04-21 08:28 UTC, goarchitecture commented on internal/db/repository.go
> +	Open() error
Open/Close это уровень DB. Репозиторию это более высокий уровень, приложение должно уметь получать-класть данные, а о том, когда открывать и закрывать - не должно интересовать

2021-04-21 08:28 UTC, goarchitecture commented on tests/server_test.go
> +	renderFactory, _ = render.NewFactory()
Есть какое-то преимущества от владения такой переменной здесь?
Можно просто каждый раз вызывать NewFactory()

Если вызов тяжелый - можно его сделать синглтоном

2021-04-22 05:23 UTC, Kolesov-Dmitry commented on internal/render/factory.go
> +		"json": NewJSONRenderer(),
Сделал

2021-04-22 05:23 UTC, Kolesov-Dmitry commented on internal/render/html_renderer.go
> +	if val.Kind() == reflect.Ptr {
Применил :)

2021-04-22 05:26 UTC, Kolesov-Dmitry commented on internal/srv/middleware.go
> +		if _, ok := query["download"]; ok {
Поправил, теперь работает и так, и так. Загрузка будет осуществляться в том случе, если флаг присутствует или выставлен в true

2021-04-22 05:26 UTC, Kolesov-Dmitry commented on internal/srv/middleware.go
> +func downloadMiddleware(h http.Handler) http.Handler {
Перенёс логику с download в ResponsWriter

2021-04-22 05:28 UTC, Kolesov-Dmitry commented on tests/server_test.go
> +	renderFactory, _ = render.NewFactory()
передедал загрузку HTML шаблонов, теперь создание фабрики - дешёвая операция

2021-04-22 05:48 UTC, Kolesov-Dmitry commented on internal/db/repository.go
> +	Open() error
Open/Close убрал

2021-04-22 07:52 UTC, goarchitecture requested changes

2021-04-22 07:52 UTC, goarchitecture commented on internal/app/app.go
> +	db     *db.BoltRepository
нет, нет. было правильно. Зачем нам зависимость от конкретной реализации. Надо зависеть от интерфейса

2021-04-22 07:52 UTC, goarchitecture commented on internal/app/app.go
> +	a.db = db.NewBoltRepository(*a.repoPath)
тут мы уже переделывали. получается несоответствие нейминга. db слева а репозиторий справа

2021-04-22 07:52 UTC, goarchitecture commented on internal/srv/response_writer.go
>  func (r *ResponseWriter) WriteDeleteSuccess() {
можно убрать метод, логику вынести в общий .Write() - просто там проверять если это был method=delete

2021-04-22 09:14 UTC, Kolesov-Dmitry commented on internal/app/app.go
> +	db     *db.BoltRepository
Я тогда не понимаю куда эту базу затолкать. Хочется всё обернуть в App, чтоб он рулил всеми сущностями (сервер, база)

2021-04-22 09:33 UTC, Kolesov-Dmitry commented on internal/app/app.go
> +	a.db = db.NewBoltRepository(*a.repoPath)
Отказался от метода Init, вынес всё в Run. Вернул обратно repo вместо db и оставил зависимость на интерфейс

2021-04-22 09:40 UTC, Kolesov-Dmitry commented on internal/srv/response_writer.go
>  func (r *ResponseWriter) WriteDeleteSuccess() {
Поправил

2021-04-23 02:31 UTC, Kolesov-Dmitry commented
Сегодня ещё закину исправлений, там Renderer будет отделён от ResponseWriter

2021-05-01 01:35 UTC, merged