Homework 4
Kolesov-Dmitry/homework pull request #4
Opened 2021-04-23 14:41 UTC by Kolesov-Dmitry

Евгений, доброго дня!

Выделил отдельнцю сущность Discount которая принимает []byte с содержимым CSV и раскладывает скидки по группам.
В Repository добавил метод Transform, который на вход принимает функцию и изменяет элементы реплозитория согласно логике работы этой функции (получился такой Visitor)

Пришлось пробросить кэш до discounter.Service, чтоб иметь возможность сбросить его содержимое после применения скидок. 
Была идея добавить в кэш некий флаг valid, затем атомарно выставлять его в false и заново перечитывать данные из репозитория. Пока valid == false кэш на Lookup возвращает nil, а на Write просто ничего не делает. Потом снова ставить valid=true. Но я не уверен, что такой подход тоже правильный....

2021-04-24 06:27 UTC, larrycinnabar requested changes
очень хорошо, но запрос небольшой рефакторинг

2021-04-24 06:27 UTC, larrycinnabar commented on internal/services/discounter/discounter.go
> +	return time.Date(now.Year(), now.Month(), now.Day(), 5, 0, 0, 0, loc).UTC()
UTC?

2021-04-24 06:27 UTC, larrycinnabar commented on internal/services/discounter/discounter.go
> +		if vendorCodeDiscount := d.DiscountByCategory(item.VendorCode); vendorCodeDiscount != 0 {
опечатка, d.DiscountByVendorCode должно быть

2021-04-24 06:27 UTC, larrycinnabar commented on internal/db/repository.go
> +	Transform(f func(*model.Item) *model.Item) error
Имеет место быть, и в целом подход должен работать (я  не запускал, но логика ясна). 
Но repo.Transform - это перегруз репозитория.
Репозитории обычно не имеют такие методы. Репозитории обычно имеют стандартные методы типа
Save, Insert, Upsert, Update, Delete, Read, ReadAll и т.д.

Transform - это уже слишком кастомно, на уровень выше.

Предлагаю разделить эти концепты, и не нагружать репозиторий.
Но репозиторий придётся изменить - тут ты прав. Текущих методов не достаточно.
Выход есть:

1) Вариант 1: мы апгрейдим метод Save. Теперь он будет создавать элемент если item.Id - пуст, и update-ить элемент, если переданный item.Id не пуст.
Минусом такого метода является то, что мы теперь запрещаем создавать элементы при условии ручного создания id (а такое бывает необходимо на практике)
2) Вариант 2: Переименовываем наш Save в Insert, и добавляем Update() который будет обновлять элемент.
(Можно оставить метод Save() - и он будет просто фасад - выбором между Insert/Update - в зависимости от наличия id)


Теперь, логика обновления скидок будет больше на DiscountService, чем на репозитории. Мы скачаем все итемы, пройдемся по ним и обновим скидку там где надо. (по сути мы выносим цикл по итемам из репозитория в DiscountService)

2021-04-24 06:42 UTC, goarchitecture requested changes
хорошо. Небольшой рефакторинг запросил.
Удали плз change-request от моего другого аккаунта

2021-04-24 06:42 UTC, goarchitecture commented on internal/app/config.go
> +	defaultDiscountURL        = "https://github.com/goarchitecture/lesson-2/blob/feature/lesson-4/assets/discounts.csv"
я дал эту ссылку так как на нее удобнее захоить человеку. А для скачивания там есть более удобный вариант

2021-04-24 06:42 UTC, goarchitecture commented on internal/db/repository.go
> +	Transform(f func(*model.Item) *model.Item) error
Имеет место быть, и в целом подход должен работать (я не запускал, но логика ясна).
Но repo.Transform - это перегруз репозитория.
Репозитории обычно не имеют такие методы. Репозитории обычно имеют стандартные методы типа
Save, Insert, Upsert, Update, Delete, Read, ReadAll и т.д.

Transform - это уже слишком кастомно, на уровень выше.

Предлагаю разделить эти концепты, и не нагружать репозиторий.
Но репозиторий придётся изменить - тут ты прав. Текущих методов не достаточно.
Выход есть:

Вариант 1: мы апгрейдим метод Save. Теперь он будет создавать элемент если item.Id - пуст, и update-ить элемент, если переданный item.Id не пуст.
Минусом такого метода является то, что мы теперь запрещаем создавать элементы при условии ручного создания id (а такое бывает необходимо на практике)
Вариант 2: Переименовываем наш Save в Insert, и добавляем Update() который будет обновлять элемент.
(Можно оставить метод Save() - и он будет просто фасад - выбором между Insert/Update - в зависимости от наличия id)
Теперь, логика обновления скидок будет больше на DiscountService, чем на репозитории. Мы скачаем все итемы, пройдемся по ним и обновим скидку там где надо. (по сути мы выносим цикл по итемам из репозитория в DiscountService)

2021-04-24 06:42 UTC, goarchitecture commented on internal/services/discounter/discount.go
> +func DiscountFromCSV(data []byte) (*Discount, error) {
не критично, но советую везде где на входе может быть строка, байты, либо содержимое файла (или другой источник), то лучше использовать io.Reader интерфейс. Более универсально и тестируемо

2021-04-24 06:42 UTC, goarchitecture commented on internal/services/discounter/discount.go
> +		if err != nil || discountValue == 0 {
группировка ошибочного варианта и допустимого варианта - не хорошо.
discountValue == 0 - поддерживаемая возможность, просто игнорим строку.
А err != nil на Atoi это уже ошибка... её надо выводить в log (если нам стали отправлять бракованные csv - мы же должны об это знать)

2021-04-24 06:42 UTC, goarchitecture commented on internal/services/discounter/discount.go
> +		discountValue, err := strconv.Atoi(line[colDiscountValue])
первую строку (заголовок) можно детектить по индексу

2021-04-24 06:42 UTC, goarchitecture commented on internal/services/discounter/discounter.go
> +		currentTimeUTC := time.Now().UTC()
можно просто `now` - распространенный паттерн называть так переменную хранящую текущее время

2021-04-24 06:42 UTC, goarchitecture commented on internal/services/discounter/discounter.go
> +		if vendorCodeDiscount := d.DiscountByCategory(item.VendorCode); vendorCodeDiscount != 0 {
опечатка, `d.DiscountByVendorCode` должно быть

2021-04-25 05:43 UTC, Kolesov-Dmitry commented on internal/services/discounter/discount.go
> +		if err != nil || discountValue == 0 {
Поправил

2021-04-25 05:43 UTC, Kolesov-Dmitry commented on internal/services/discounter/discount.go
> +		discountValue, err := strconv.Atoi(line[colDiscountValue])
Сделал

2021-04-25 06:03 UTC, Kolesov-Dmitry commented on internal/db/repository.go
> +	Transform(f func(*model.Item) *model.Item) error
У меня задумка была в том, что Transform выполняет за одну транзакцию, Т.е. у меня либо скидки применяются ко всем товарам, либо вообще не применяются. C Update выходит так, что каждый update это одна транзакция и теперь кэш станоывится невалидный "постепенно", а не сразу весь. 

Опять же мне сложно судить как правильно, а как нет, в моей предметной области (мы пишем ПО для ЦУП) кэш не актуальная тема и вообще не применяется :)

Итого, переделал на Update, но метод Transform пока выпиливать не буду :)

2021-04-25 06:03 UTC, Kolesov-Dmitry commented on internal/services/discounter/discounter.go
> +		if vendorCodeDiscount := d.DiscountByCategory(item.VendorCode); vendorCodeDiscount != 0 {
Поправил

2021-04-25 06:05 UTC, Kolesov-Dmitry commented on internal/app/config.go
> +	defaultDiscountURL        = "https://github.com/goarchitecture/lesson-2/blob/feature/lesson-4/assets/discounts.csv"
Я не нашёл других ссылок на этот файл, но вообще специльно вынес его в настройки, чтоб можно было указывать при запуске приложения

2021-04-25 06:06 UTC, Kolesov-Dmitry commented
> Удали плз change-request от моего другого аккаунта

Гитхаб не даёт мне этого сделать (((

2021-04-25 11:54 UTC, Kolesov-Dmitry commented on internal/services/discounter/discount.go
> +func DiscountFromCSV(data []byte) (*Discount, error) {
Переделал

2021-04-30 19:45 UTC, goarchitecture commented on internal/db/repository.go
> +	Transform(f func(*model.Item) *model.Item) error
Главный нюанс был в том, что функция Transform(cb) - не такого метода обычно в репозиториях. нигде не встречал.
Я про то, что этот метод в принципе то может существовать, но его уровень - не репозиторий, а уровень выше (над репозиторием)

Да, понимаю, что так как кеш у нас надстройка над репо, и если мы выносим Transform из репо, то получается что кэш инвалидируется "чаще".
Но так и должно быть. 

Transform не может существовать в репо ещё и в принципе в таком виде. Он без фильтровый,  то есть он пробегает ВСЕ объекты. В реальных условиях, там могут быть миллионы записей. Исполнение такого трансформа может длиться десятки минут. За это время понятно что кеш может уже сто раз перезаписаться.

2021-04-30 20:07 UTC, goarchitecture approved these changes

2021-05-01 01:35 UTC, merged

2021-05-01 03:11 UTC, goarchitecture commented on internal/services/discounter/discounter.go
> +	for _, item := range items {
UPD:
Вообще, конечно с тчоки зрения оптимизации алгоритм должен в другом направлении немного:

На практике, товаров в БД может быть миллионов. А файл с сегодняшними скидками - в нём будут сотни - тысячи элементов (тем более многие скидки будут даваться на всю категорию, а не на отдельные товары)

Лучше конечно расширить репозиторий, дать ему методы: FindByVendorCode() и FindAllByCategory()
И цикл делать наоборот: по всем скидкам что есть - находить объекты, к которым нужно применить скидку X, и применять его:

```
for _, discount := range discounts {
catItems := repository.FindByCategory(discount.category)
for _, item := range catitems {
// apply discount to item
}
````

2021-05-03 01:44 UTC, Kolesov-Dmitry commented on internal/services/discounter/discounter.go
> +	for _, item := range items {
Да, я так и думал сделать, но у нас в конце CSV файла есть строка "скидка на все товары" + надо сбрасывать скидку "с прошлого дня", потому так и так придется по всем строкам в БД пройтись.