Homework-5
Kolesov-Dmitry/homework pull request #5
Opened 2021-04-27 11:46 UTC by Kolesov-Dmitry

Добрый день, Евгений!

Я всё же решил оствить поле parent в структуре Category. Так гораздо проще обходить дерево в обратном направлении (от подкатегории к корню). 

Ещё методы Root и BreadCrumbs выполнил в виде рекурсии. Если вдруг рекурсия фу-фу-фу и очень плохо, могу развернуть в циклы, но как по мне так код выглядит аккуратней.

Метод Parent докинул уже просто чтоб был, понадобится (а может и нет) потом когда буду сохранять/грузить категории в/из БД.

2021-04-27 12:51 UTC, goarchitecture requested changes
очень хорошо. Жду небольшого рефакторинга.

2021-04-27 12:51 UTC, goarchitecture commented on internal/model/category.go
> +	parent   *Category
конечно, держать указатель на родителя во внутреннем поле - верное решение

2021-04-27 12:51 UTC, goarchitecture commented on internal/model/category.go
> +func (c *Category) BreadCrumbs() string {
пусть BreadCrumbs возвращает слайс категорий.
Тогда с помощью кастомного типа и хелпер функций вы можете выводить любые виды строк (используя c.Name,c.Slug,c.Id и т.д.) (а не привязываться строго к c.Name и `/` как разделитель)

2021-04-27 15:08 UTC, Kolesov-Dmitry commented on internal/model/category.go
> +func (c *Category) BreadCrumbs() string {
Поправил

2021-04-29 05:48 UTC, goarchitecture commented on internal/model/category.go
> +func (c *Category) BreadCrumbs() string {
Хотя, посмотрел на эту с другой стороны.
Наш тип `[]*Category` получается хранит список деревьев. Ведь каждая Category - хранит в себе указатель на родителя и так.

Можно просто добавить методы:
`category.Slugs()`, `category.Names()`, `category.Ids` - которые будут возвращать список слагов, имён или id-шников соответственно.

Тогда `category.Breadcrumbs` будет действительно возвращать string как ты сначала указал. `category.Breadcrumbs` будет просто фасадом вокруг `category.Names()` который склеивает список именов  в одну строку по заданному "клею" (`>` или ` / ` по дефолту к примеру)

Получается что пользователю можно будет воспользоваться `category.Breadcrumbs()` или же создать уже кастомную свою на основе `category.Names()` или `category.Slugs()` и т.д.

2021-04-29 05:49 UTC, goarchitecture commented on internal/model/category.go
> +func (c *Category) BreadCrumbs() string {
P.S. оцененные ДЗ (а насколько я помню оцененны уже все) - надо мерджить.
Так что в твоем случае всё ДЗ может быть уже полностью в main ветке

2021-04-30 00:45 UTC, Kolesov-Dmitry commented on internal/model/category.go
> +func (c *Category) BreadCrumbs() string {
Третье и четвёртое без оценки ещё 😇

2021-05-01 01:34 UTC, merged